#!/usr/bin/env bash
# Manifest state manager: tracks installed tools and sync history
# Usage: bash runtime/manifest.sh <command> [args]
# Commands: init, read, update <tool-id> <status>, diff <merged-config-file>, status
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
MANIFEST="$REPO_ROOT/runtime/manifest.yaml"
LOCKFILE="/tmp/ai-config-os-manifest.lock"
COMMAND="${1:?Usage: manifest.sh <command> [args]}"

if ! command -v yq &>/dev/null; then
  echo "[error] yq required" >&2; exit 1
fi

# Acquire lock with timeout (prevents concurrent sync races)
acquire_lock() {
  local timeout=10
  local waited=0
  while [ -f "$LOCKFILE" ] && [ $waited -lt $timeout ]; do
    sleep 1
    waited=$((waited + 1))
  done
  if [ -f "$LOCKFILE" ]; then
    echo "[error] Could not acquire manifest lock after ${timeout}s. Another sync may be running." >&2
    exit 1
  fi
  echo $$ > "$LOCKFILE"
  trap "rm -f $LOCKFILE" EXIT
}

atomic_write() {
  local file="$1"
  local content="$2"
  local tmp="${file}.tmp.$$"
  echo "$content" > "$tmp"
  mv "$tmp" "$file"
}

case "$COMMAND" in
  init)
    if [ -f "$MANIFEST" ]; then
      echo "[info] Manifest already exists at $MANIFEST"
      exit 0
    fi
    acquire_lock
    atomic_write "$MANIFEST" "$(cat <<EOF
# ai-config-os runtime manifest
# Auto-generated by runtime/manifest.sh — do not edit manually
created_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
last_synced: null
device: "$(hostname 2>/dev/null || echo 'unknown')"
tools: {}
feature_flags:
  outcome_resolution_enabled: false
  effective_contract_required: false
  remote_executor_enabled: false
EOF
)"
    echo "[ok] Manifest initialised at $MANIFEST"
    ;;

  read)
    [ -f "$MANIFEST" ] && cat "$MANIFEST" || echo "[info] No manifest yet. Run: bash runtime/manifest.sh init"
    ;;

  update)
    TOOL_ID="${2:?update requires tool-id}"
    STATUS="${3:?update requires status}"
    acquire_lock
    [ ! -f "$MANIFEST" ] && bash "$0" init
    updated=$(yq ".tools[\"$TOOL_ID\"] = {\"status\": \"$STATUS\", \"last_updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" "$MANIFEST")
    atomic_write "$MANIFEST" "$updated"
    echo "[ok] Updated manifest: $TOOL_ID = $STATUS"
    ;;

  diff)
    MERGED_CONFIG="${2:?diff requires merged config file path}"
    [ ! -f "$MANIFEST" ] && bash "$0" init
    echo "==> Manifest diff (desired vs installed)"
    echo ""
    # Compare desired MCP servers against manifest
    desired_mcps=$(yq '.mcps // {} | keys[]' "$MERGED_CONFIG" 2>/dev/null || echo "")
    if [ -n "$desired_mcps" ]; then
      echo "MCP servers desired:"
      echo "$desired_mcps" | while read -r name; do
        installed=$(yq ".tools[\"$name\"].status // \"not-installed\"" "$MANIFEST" 2>/dev/null || echo "not-installed")
        echo "  $name: $installed"
      done
    else
      echo "No MCP servers in desired config"
    fi
    ;;

  status)
    [ ! -f "$MANIFEST" ] && echo "[info] No manifest. Run: bash runtime/manifest.sh init" && exit 0
    echo "==> Runtime manifest status"
    echo "Device: $(yq -r '.device' "$MANIFEST")"
    echo "Last synced: $(yq -r '.last_synced // "never"' "$MANIFEST")"
    echo ""
    echo "Feature flags:"
    yq -r '.feature_flags | to_entries[] | "  \(.key): \(.value)"' "$MANIFEST" 2>/dev/null || true
    echo ""
    tool_count=$(yq '.tools | length' "$MANIFEST" 2>/dev/null || echo 0)
    if [ "$tool_count" -gt 0 ]; then
      echo "Tracked tools:"
      yq -r '.tools | to_entries[] | "  \(.key): \(.value.status) (updated: \(.value.last_updated))"' "$MANIFEST"
    else
      echo "No tools tracked yet"
    fi
    ;;

  *)
    echo "[error] Unknown command: $COMMAND" >&2
    exit 1
    ;;
esac
