/**
 * ai-config-os Cloudflare Worker
 *
 * Distributes compiled skill artefacts to authenticated clients.
 * Artefacts are bundled at deploy time from dist/ (generated by compile.mjs).
 *
 * API surface:
 *   GET /v1/health
 *   GET /v1/manifest/latest
 *   GET /v1/client/:client/latest
 *   GET /v1/skill/:skillId
 *
 * Auth: Authorization: Bearer <token> on all endpoints.
 * Tokens: AUTH_TOKEN (primary), AUTH_TOKEN_NEXT (rotation staging).
 */

// Bundled at deploy time by wrangler from dist/
// @ts-ignore - generated at build time
import REGISTRY_JSON from '../../dist/registry/index.json';
// @ts-ignore - generated at build time
import CLAUDE_CODE_PLUGIN_JSON from '../../dist/clients/claude-code/.claude-plugin/plugin.json';

export interface Env {
  AUTH_TOKEN: string;
  AUTH_TOKEN_NEXT?: string;
  ENVIRONMENT?: string;
}

// ── Auth ──────────────────────────────────────────────────────────────────

function isAuthorized(request: Request, env: Env): boolean {
  const authHeader = request.headers.get('Authorization') ?? '';
  if (!authHeader.startsWith('Bearer ')) return false;
  const token = authHeader.slice(7).trim();
  if (!token) return false;
  if (token === env.AUTH_TOKEN) return true;
  if (env.AUTH_TOKEN_NEXT && token === env.AUTH_TOKEN_NEXT) return true;
  return false;
}

function unauthorizedResponse(): Response {
  return new Response(
    JSON.stringify({ error: 'Unauthorized', hint: 'Provide a valid Bearer token' }),
    {
      status: 401,
      headers: {
        'Content-Type': 'application/json',
        'WWW-Authenticate': 'Bearer realm="ai-config-os"',
      },
    }
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

function notFound(message: string): Response {
  return jsonResponse({ error: 'Not Found', message }, 404);
}

// ── Route handlers ────────────────────────────────────────────────────────

function handleHealth(env: Env): Response {
  return jsonResponse({
    status: 'ok',
    version: (REGISTRY_JSON as any).version,
    built_at: (REGISTRY_JSON as any).built_at,
    environment: env.ENVIRONMENT ?? 'unknown',
  });
}

function handleManifestLatest(): Response {
  return jsonResponse(REGISTRY_JSON);
}

function handleClientLatest(client: string): Response {
  if (client !== 'claude-code') {
    return notFound(`Client '${client}' not found. Available: claude-code`);
  }

  const registry = REGISTRY_JSON as any;

  // Build artefact map: plugin.json + skill SKILL.md content
  // Skills content is not bundled as separate static imports (too many files).
  // Instead, we return the plugin.json and skill listing; clients fetch
  // individual skills via /v1/skill/:skillId if needed.
  const response = {
    version: registry.version,
    built_at: registry.built_at,
    client: 'claude-code',
    plugin_json: CLAUDE_CODE_PLUGIN_JSON,
    skills: registry.skills,
    note: 'Fetch individual skill content via GET /v1/skill/:skillId',
  };

  return jsonResponse(response);
}

function handleSkill(skillId: string): Response {
  const registry = REGISTRY_JSON as any;
  const skill = (registry.skills as any[]).find((s: any) => s.id === skillId);

  if (!skill) {
    return notFound(`Skill '${skillId}' not found`);
  }

  return jsonResponse({
    version: registry.version,
    skill,
  });
}

// ── Router ────────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, OPTIONS',
          'Access-Control-Allow-Headers': 'Authorization',
        },
      });
    }

    if (request.method !== 'GET') {
      return jsonResponse({ error: 'Method Not Allowed' }, 405);
    }

    const url = new URL(request.url);
    const path = url.pathname;

    // Auth guard (all endpoints)
    if (!isAuthorized(request, env)) {
      return unauthorizedResponse();
    }

    // Routes
    if (path === '/v1/health') {
      return handleHealth(env);
    }

    if (path === '/v1/manifest/latest') {
      return handleManifestLatest();
    }

    const clientMatch = path.match(/^\/v1\/client\/([^/]+)\/latest$/);
    if (clientMatch) {
      return handleClientLatest(clientMatch[1]);
    }

    const skillMatch = path.match(/^\/v1\/skill\/([^/]+)$/);
    if (skillMatch) {
      return handleSkill(skillMatch[1]);
    }

    return notFound(`Unknown route: ${path}`);
  },
} satisfies ExportedHandler<Env>;
