/**
 * ai-config-os Cloudflare Worker
 *
 * Distributes compiled skill artefacts to authenticated clients.
 * Artefacts are bundled at deploy time from dist/ (generated by compile.mjs).
 *
 * API surface:
 *   GET /v1/health
 *   GET /v1/manifest/latest
 *   GET /v1/outcomes/latest
 *   GET /v1/outcomes/:version
 *   GET /v1/routes/latest
 *   GET /v1/routes/:version
 *   GET /v1/tools/latest
 *   GET /v1/tools/:version
 *   GET /v1/effective-contract/preview
 *   GET /v1/client/:client/latest
 *   GET /v1/skill/:skillId
 *   POST /v1/execute
 *
 * Auth: Authorization: Bearer <token> on all endpoints.
 * Tokens: AUTH_TOKEN (primary), AUTH_TOKEN_NEXT (rotation staging).
 */

// Bundled at deploy time by wrangler from dist/
// @ts-ignore - generated at build time
import REGISTRY_JSON from '../../dist/registry/index.json';
// @ts-ignore - generated at build time
import CLAUDE_CODE_PLUGIN_JSON from '../../dist/clients/claude-code/.claude-plugin/plugin.json';

export interface Env {
  AUTH_TOKEN: string;
  AUTH_TOKEN_NEXT?: string;
  ENVIRONMENT?: string;
  EXECUTOR_PROXY_URL: string;
  EXECUTOR_SHARED_SECRET: string;
  EXECUTOR_TIMEOUT_MS?: string;
  MANIFEST_KV?: {
    get(key: string): Promise<string | null> | string | null;
  };
  ARTEFACTS_R2?: {
    get(key: string): Promise<{ text(): Promise<string> } | null> | { text(): Promise<string> } | null;
  };
}

type ExecutePayload = {
  request_id?: string;
  tool: string;
  args?: string[];
  timeout_ms?: number;
  metadata?: Record<string, unknown>;
};

// ── Auth ──────────────────────────────────────────────────────────────────

function isAuthorized(request: Request, env: Env): boolean {
  const authHeader = request.headers.get('Authorization') ?? '';
  if (!authHeader.startsWith('Bearer ')) return false;
  const token = authHeader.slice(7).trim();
  if (!token) return false;
  if (token === env.AUTH_TOKEN) return true;
  if (env.AUTH_TOKEN_NEXT && token === env.AUTH_TOKEN_NEXT) return true;
  return false;
}

function unauthorizedResponse(): Response {
  return new Response(
    JSON.stringify({ error: 'Unauthorized', hint: 'Provide a valid Bearer token' }),
    {
      status: 401,
      headers: {
        'Content-Type': 'application/json',
        'WWW-Authenticate': 'Bearer realm="ai-config-os"',
      },
    }
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

function notFound(message: string): Response {
  return jsonResponse({ error: 'Not Found', message }, 404);
}

function parseTimeoutMs(raw: string | undefined): number {
  const parsed = Number(raw ?? '10000');
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return 10000;
  }
  return Math.min(parsed, 120000);
}

async function readLatestVersion(env: Env): Promise<string | Response> {
  if (!env.MANIFEST_KV) {
    return (REGISTRY_JSON as any).version;
  }

  const version = await env.MANIFEST_KV.get('latest');
  if (typeof version !== 'string' || version.length === 0) {
    return jsonResponse({ error: 'Latest manifest version pointer missing' }, 503);
  }

  return version;
}

async function readArtifactJson(env: Env, key: string): Promise<unknown | Response> {
  if (!env.ARTEFACTS_R2) {
    return jsonResponse({ error: 'Manifest artefact storage is not configured' }, 503);
  }

  const object = await env.ARTEFACTS_R2.get(key);
  if (!object) {
    return notFound(`Artifact not found for key '${key}'`);
  }

  const text = await object.text();
  try {
    return JSON.parse(text);
  } catch {
    return jsonResponse({ error: `Artifact '${key}' contains invalid JSON` }, 502);
  }
}

function validateExecutePayload(payload: unknown): { ok: true; value: ExecutePayload } | { ok: false; error: string } {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, error: 'Payload must be a JSON object' };
  }

  const data = payload as Record<string, unknown>;

  if (typeof data.tool !== 'string' || data.tool.trim().length === 0) {
    return { ok: false, error: "Field 'tool' must be a non-empty string" };
  }

  if (
    data.args !== undefined
    && (!Array.isArray(data.args) || data.args.some((arg) => typeof arg !== 'string'))
  ) {
    return { ok: false, error: "Field 'args' must be an array of strings" };
  }

  if (
    data.timeout_ms !== undefined
    && (!Number.isInteger(data.timeout_ms) || Number(data.timeout_ms) <= 0)
  ) {
    return { ok: false, error: "Field 'timeout_ms' must be a positive integer" };
  }

  if (data.request_id !== undefined && typeof data.request_id !== 'string') {
    return { ok: false, error: "Field 'request_id' must be a string" };
  }

  if (
    data.metadata !== undefined
    && (typeof data.metadata !== 'object' || data.metadata === null || Array.isArray(data.metadata))
  ) {
    return { ok: false, error: "Field 'metadata' must be an object" };
  }

  return {
    ok: true,
    value: {
      request_id: data.request_id as string | undefined,
      tool: data.tool,
      args: data.args as string[] | undefined,
      timeout_ms: data.timeout_ms as number | undefined,
      metadata: data.metadata as Record<string, unknown> | undefined,
    },
  };
}

// ── Route handlers ────────────────────────────────────────────────────────

function handleHealth(env: Env): Response {
  return jsonResponse({
    status: 'ok',
    version: (REGISTRY_JSON as any).version,
    built_at: (REGISTRY_JSON as any).built_at,
    environment: env.ENVIRONMENT ?? 'unknown',
  });
}

async function handleManifestLatest(env: Env): Promise<Response> {
  if (!env.MANIFEST_KV || !env.ARTEFACTS_R2) {
    return jsonResponse(REGISTRY_JSON);
  }

  const version = await readLatestVersion(env);
  if (version instanceof Response) {
    return version;
  }

  const key = `manifests/${version}/manifest.json`;
  const manifest = await readArtifactJson(env, key);
  if (manifest instanceof Response) {
    return manifest;
  }

  return jsonResponse({
    version,
    key,
    manifest,
  });
}

async function handleVersionedArtifact(env: Env, version: string, artifactName: string): Promise<Response> {
  const key = `manifests/${version}/${artifactName}`;
  const artifact = await readArtifactJson(env, key);
  if (artifact instanceof Response) {
    return artifact;
  }

  return jsonResponse({ version, key, artifact });
}

async function handleLatestArtifact(env: Env, artifactName: string): Promise<Response> {
  const version = await readLatestVersion(env);
  if (version instanceof Response) {
    return version;
  }

  return handleVersionedArtifact(env, version, artifactName);
}

async function handleEffectiveContractPreview(env: Env): Promise<Response> {
  const version = await readLatestVersion(env);
  if (version instanceof Response) {
    return version;
  }

  const outcomesKey = `manifests/${version}/outcomes.json`;
  const routesKey = `manifests/${version}/routes.json`;
  const toolsKey = `manifests/${version}/tools.json`;

  const outcomes = await readArtifactJson(env, outcomesKey);
  if (outcomes instanceof Response) return outcomes;

  const routes = await readArtifactJson(env, routesKey);
  if (routes instanceof Response) return routes;

  const tools = await readArtifactJson(env, toolsKey);
  if (tools instanceof Response) return tools;

  return jsonResponse({
    version,
    sources: {
      outcomes: outcomesKey,
      routes: routesKey,
      tools: toolsKey,
    },
    effective_contract: {
      outcomes,
      routes,
      tools,
    },
  });
}

function handleClientLatest(client: string): Response {
  if (client !== 'claude-code') {
    return notFound(`Client '${client}' not found. Available: claude-code`);
  }

  const registry = REGISTRY_JSON as any;

  const response = {
    version: registry.version,
    built_at: registry.built_at,
    client: 'claude-code',
    plugin_json: CLAUDE_CODE_PLUGIN_JSON,
    skills: registry.skills,
    note: 'Fetch individual skill content via GET /v1/skill/:skillId',
  };

  return jsonResponse(response);
}

function handleSkill(skillId: string): Response {
  const registry = REGISTRY_JSON as any;
  const skill = (registry.skills as any[]).find((s: any) => s.id === skillId);

  if (!skill) {
    return notFound(`Skill '${skillId}' not found`);
  }

  return jsonResponse({
    version: registry.version,
    skill,
  });
}

async function handleExecute(request: Request, env: Env): Promise<Response> {
  if (!env.EXECUTOR_PROXY_URL || !env.EXECUTOR_SHARED_SECRET) {
    return jsonResponse({ error: 'Executor proxy is not configured' }, 500);
  }

  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return jsonResponse({ error: 'Invalid JSON body' }, 400);
  }

  const validation = validateExecutePayload(payload);
  if (!validation.ok) {
    return jsonResponse({ error: validation.error }, 400);
  }

  const timeoutMs = parseTimeoutMs(env.EXECUTOR_TIMEOUT_MS);
  const forwardedSignature = request.headers.get('X-Request-Signature') ?? '';

  try {
    const response = await fetch(`${env.EXECUTOR_PROXY_URL.replace(/\/$/, '')}/v1/execute`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Executor-Shared-Secret': env.EXECUTOR_SHARED_SECRET,
        'X-Request-Signature': forwardedSignature,
      },
      body: JSON.stringify(validation.value),
      signal: AbortSignal.timeout(timeoutMs),
    });

    const responseBody: Record<string, unknown> = await response
      .json()
      .then((body) => (typeof body === 'object' && body !== null ? body as Record<string, unknown> : {}))
      .catch(() => ({}));

    return jsonResponse({
      ok: response.ok,
      status: response.status,
      result: responseBody.result ?? null,
      error: response.ok
        ? null
        : (responseBody.error ?? { code: 'UPSTREAM_ERROR', message: 'Executor returned an error' }),
      request_id: validation.value.request_id ?? null,
    }, response.ok ? 200 : response.status);
  } catch {
    return jsonResponse({
      ok: false,
      status: 504,
      error: { code: 'UPSTREAM_TIMEOUT', message: 'Executor request timed out or failed' },
      request_id: validation.value.request_id ?? null,
    }, 504);
  }
}

// ── Router ────────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Authorization, Content-Type, X-Request-Signature',
        },
      });
    }

    const url = new URL(request.url);
    const path = url.pathname;

    if (!isAuthorized(request, env)) {
      return unauthorizedResponse();
    }

    if (request.method === 'GET') {
      if (path === '/v1/health') {
        return handleHealth(env);
      }

      if (path === '/v1/manifest/latest') {
        return handleManifestLatest(env);
      }

      if (path === '/v1/outcomes/latest') {
        return handleLatestArtifact(env, 'outcomes.json');
      }

      if (path === '/v1/routes/latest') {
        return handleLatestArtifact(env, 'routes.json');
      }

      if (path === '/v1/tools/latest') {
        return handleLatestArtifact(env, 'tools.json');
      }

      const outcomesVersionedMatch = path.match(/^\/v1\/outcomes\/([^/]+)$/);
      if (outcomesVersionedMatch) {
        return handleVersionedArtifact(env, outcomesVersionedMatch[1], 'outcomes.json');
      }

      const routesVersionedMatch = path.match(/^\/v1\/routes\/([^/]+)$/);
      if (routesVersionedMatch) {
        return handleVersionedArtifact(env, routesVersionedMatch[1], 'routes.json');
      }

      const toolsVersionedMatch = path.match(/^\/v1\/tools\/([^/]+)$/);
      if (toolsVersionedMatch) {
        return handleVersionedArtifact(env, toolsVersionedMatch[1], 'tools.json');
      }

      if (path === '/v1/effective-contract/preview') {
        return handleEffectiveContractPreview(env);
      }

      const clientMatch = path.match(/^\/v1\/client\/([^/]+)\/latest$/);
      if (clientMatch) {
        return handleClientLatest(clientMatch[1]);
      }

      const skillMatch = path.match(/^\/v1\/skill\/([^/]+)$/);
      if (skillMatch) {
        return handleSkill(skillMatch[1]);
      }
    }

    if (request.method === 'POST' && path === '/v1/execute') {
      return handleExecute(request, env);
    }

    if (request.method !== 'GET' && request.method !== 'POST') {
      return jsonResponse({ error: 'Method Not Allowed' }, 405);
    }

    return notFound(`Unknown route: ${path}`);
  },
} satisfies ExportedHandler<Env>;
