/**
 * ai-config-os Cloudflare Worker
 *
 * Distributes compiled skill artefacts to authenticated clients.
 * Artefacts are bundled at deploy time from dist/ (generated by compile.mjs).
 *
 * API surface:
 *   GET /v1/health
 *   GET /v1/manifest/latest
 *   GET /v1/outcomes/latest
 *   GET /v1/outcomes/:version
 *   GET /v1/routes/latest
 *   GET /v1/routes/:version
 *   GET /v1/tools/latest
 *   GET /v1/tools/:version
 *   GET /v1/effective-contract/preview
 *   GET /v1/client/:client/latest
 *   GET /v1/skill/:skillId
 *
 * Auth: Authorization: Bearer <token> on all endpoints.
 * Tokens: AUTH_TOKEN (primary), AUTH_TOKEN_NEXT (rotation staging).
 */

// Bundled at deploy time by wrangler from dist/
// @ts-ignore - generated at build time
import REGISTRY_JSON from '../../dist/registry/index.json';
// @ts-ignore - generated at build time
import CLAUDE_CODE_PLUGIN_JSON from '../../dist/clients/claude-code/.claude-plugin/plugin.json';
import { makeErrorResponse } from '../../packages/contracts/index.js';

export interface Env {
  AUTH_TOKEN: string;
  AUTH_TOKEN_NEXT?: string;
  ENVIRONMENT?: string;
  MANIFEST_KV: KVNamespace;
  ARTEFACTS_R2: R2Bucket;
}

// ── Auth ──────────────────────────────────────────────────────────────────

function isAuthorized(request: Request, env: Env): boolean {
  const authHeader = request.headers.get('Authorization') ?? '';
  if (!authHeader.startsWith('Bearer ')) return false;
  const token = authHeader.slice(7).trim();
  if (!token) return false;
  if (token === env.AUTH_TOKEN) return true;
  if (env.AUTH_TOKEN_NEXT && token === env.AUTH_TOKEN_NEXT) return true;
  return false;
}

function unauthorizedResponse(): Response {
  return new Response(
    JSON.stringify(makeErrorResponse({
      code: 'UNAUTHORIZED',
      message: 'Unauthorized',
      details: { hint: 'Provide a valid Bearer token' },
    })),
    {
      status: 401,
      headers: {
        'Content-Type': 'application/json',
        'WWW-Authenticate': 'Bearer realm="ai-config-os"',
      },
    }
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

function notFound(message: string): Response {
  return jsonResponse(makeErrorResponse({ code: 'NOT_FOUND', message, details: { status: 404 } }), 404);
}

function unprocessableEntity(message: string, diagnostics?: Record<string, unknown>): Response {
  return jsonResponse({ error: 'Unprocessable Entity', message, diagnostics }, 422);
}

type ResolvedVersion = {
  version: string;
  source: 'query' | 'kv';
  key?: string;
};

async function resolveVersion(url: URL, env: Env): Promise<ResolvedVersion | Response> {
  const requestedVersion = url.searchParams.get('version')?.trim();
  if (requestedVersion) {
    return {
      version: requestedVersion,
      source: 'query',
    };
  }

  const pointerKey = 'manifest:latest';
  const latestVersion = (await env.MANIFEST_KV.get(pointerKey))?.trim();
  if (!latestVersion) {
    return notFound(`Latest manifest pointer '${pointerKey}' is missing`);
  }

  return {
    version: latestVersion,
    source: 'kv',
    key: pointerKey,
  };
}

type ArtifactFetchResult = {
  name: 'outcomes' | 'routes' | 'tools' | 'contract_template';
  key: string;
  data: unknown;
};

async function fetchArtifactJson(
  env: Env,
  name: ArtifactFetchResult['name'],
  keyCandidates: string[],
  required: boolean
): Promise<ArtifactFetchResult | { response: Response }> {
  for (const key of keyCandidates) {
    const object = await env.ARTEFACTS_R2.get(key);
    if (!object) continue;

    try {
      const data = await object.json();
      return { name, key, data };
    } catch {
      return {
        response: unprocessableEntity(`Artifact '${name}' is not valid JSON`, { key }),
      };
    }
  }

  if (!required) {
    return {
      name,
      key: '',
      data: null,
    };
  }

  return {
    response: notFound(
      `Required artifact '${name}' was not found for any expected R2 key candidate`
    ),
  };
}

async function handleEffectiveContractPreview(url: URL, env: Env): Promise<Response> {
  const resolvedVersion = await resolveVersion(url, env);
  if (resolvedVersion instanceof Response) {
    return resolvedVersion;
  }

  const version = resolvedVersion.version;

  const outcomes = await fetchArtifactJson(
    env,
    'outcomes',
    [
      `versions/${version}/outcomes.json`,
      `${version}/outcomes.json`,
      `outcomes/${version}.json`,
    ],
    true
  );
  if ('response' in outcomes) return outcomes.response;

  const routes = await fetchArtifactJson(
    env,
    'routes',
    [`versions/${version}/routes.json`, `${version}/routes.json`, `routes/${version}.json`],
    true
  );
  if ('response' in routes) return routes.response;

  const tools = await fetchArtifactJson(
    env,
    'tools',
    [`versions/${version}/tools.json`, `${version}/tools.json`, `tools/${version}.json`],
    true
  );
  if ('response' in tools) return tools.response;

  const contractTemplate = await fetchArtifactJson(
    env,
    'contract_template',
    [
      `versions/${version}/contract-template.json`,
      `${version}/contract-template.json`,
      `contracts/${version}.template.json`,
    ],
    false
  );
  if ('response' in contractTemplate) return contractTemplate.response;

  const preview = {
    contract_template: contractTemplate.data,
    outcomes: outcomes.data,
    routes: routes.data,
    tools: tools.data,
  };

  return jsonResponse({
    version,
    provenance: {
      version_source: resolvedVersion.source,
      version_pointer_key: resolvedVersion.key ?? null,
      source_keys: {
        outcomes: outcomes.key,
        routes: routes.key,
        tools: tools.key,
        contract_template: contractTemplate.key || null,
      },
    },
    preview,
  });
}

// ── Route handlers ────────────────────────────────────────────────────────

function handleHealth(env: Env): Response {
  return jsonResponse({
    status: 'ok',
    version: (REGISTRY_JSON as any).version,
    built_at: (REGISTRY_JSON as any).built_at,
    environment: env.ENVIRONMENT ?? 'unknown',
  });
}

async function handleManifestLatest(env: Env): Promise<Response> {
  if (!env.MANIFEST_POINTERS || !env.MANIFEST_ARTIFACTS) {
    return jsonResponse(REGISTRY_JSON);
  }

  const version = await readLatestVersion(env);
  if (version instanceof Response) {
    return version;
  }

  const key = `manifests/${version}/manifest.json`;
  const manifest = await readArtifactJson(env, key);
  if (manifest instanceof Response) {
    return manifest;
  }

  return jsonResponse({
    version,
    key,
    manifest,
  });
}

async function handleVersionedArtifact(env: Env, version: string, artifactName: string): Promise<Response> {
  const key = `manifests/${version}/${artifactName}`;
  const artifact = await readArtifactJson(env, key);
  if (artifact instanceof Response) {
    return artifact;
  }

  return jsonResponse({ version, key, artifact });
}

async function handleLatestArtifact(env: Env, artifactName: string): Promise<Response> {
  const version = await readLatestVersion(env);
  if (version instanceof Response) {
    return version;
  }

  return handleVersionedArtifact(env, version, artifactName);
}

async function handleEffectiveContractPreview(env: Env): Promise<Response> {
  const version = await readLatestVersion(env);
  if (version instanceof Response) {
    return version;
  }

  const outcomesKey = `manifests/${version}/outcomes.json`;
  const routesKey = `manifests/${version}/routes.json`;
  const toolsKey = `manifests/${version}/tools.json`;

  const outcomes = await readArtifactJson(env, outcomesKey);
  if (outcomes instanceof Response) return outcomes;

  const routes = await readArtifactJson(env, routesKey);
  if (routes instanceof Response) return routes;

  const tools = await readArtifactJson(env, toolsKey);
  if (tools instanceof Response) return tools;

  return jsonResponse({
    version,
    sources: {
      outcomes: outcomesKey,
      routes: routesKey,
      tools: toolsKey,
    },
    effective_contract: {
      outcomes,
      routes,
      tools,
    },
  });
}

function handleClientLatest(client: string): Response {
  if (client !== 'claude-code') {
    return notFound(`Client '${client}' not found. Available: claude-code`);
  }

  const registry = REGISTRY_JSON as any;

  // Build artefact map: plugin.json + skill SKILL.md content
  // Skills content is not bundled as separate static imports (too many files).
  // Instead, we return the plugin.json and skill listing; clients fetch
  // individual skills via /v1/skill/:skillId if needed.
  const response = {
    version: registry.version,
    built_at: registry.built_at,
    client: 'claude-code',
    plugin_json: CLAUDE_CODE_PLUGIN_JSON,
    skills: registry.skills,
    note: 'Fetch individual skill content via GET /v1/skill/:skillId',
  };

  return jsonResponse(response);
}

function handleSkill(skillId: string): Response {
  const registry = REGISTRY_JSON as any;
  const skill = (registry.skills as any[]).find((s: any) => s.id === skillId);

  if (!skill) {
    return notFound(`Skill '${skillId}' not found`);
  }

  return jsonResponse({
    version: registry.version,
    skill,
  });
}

// ── Router ────────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, OPTIONS',
          'Access-Control-Allow-Headers': 'Authorization',
        },
      });
    }

    if (request.method !== 'GET') {
      return jsonResponse(makeErrorResponse({ code: 'METHOD_NOT_ALLOWED', message: 'Method Not Allowed', details: { method: request.method } }), 405);
    }

    const url = new URL(request.url);
    const path = url.pathname;

    // Auth guard (all endpoints)
    if (!isAuthorized(request, env)) {
      return unauthorizedResponse();
    }

    // Routes
    if (path === '/v1/health') {
      return handleHealth(env);
    }

    if (path === '/v1/manifest/latest') {
      return handleManifestLatest(env);
    }

    if (path === '/v1/outcomes/latest') {
      return handleLatestArtifact(env, 'outcomes.json');
    }

    if (path === '/v1/routes/latest') {
      return handleLatestArtifact(env, 'routes.json');
    }

    if (path === '/v1/tools/latest') {
      return handleLatestArtifact(env, 'tools.json');
    }

    if (path === '/v1/effective-contract/preview') {
      return handleEffectiveContractPreview(env);
    }

    const outcomesVersionMatch = path.match(/^\/v1\/outcomes\/([^/]+)$/);
    if (outcomesVersionMatch) {
      return handleVersionedArtifact(env, outcomesVersionMatch[1], 'outcomes.json');
    }

    const routesVersionMatch = path.match(/^\/v1\/routes\/([^/]+)$/);
    if (routesVersionMatch) {
      return handleVersionedArtifact(env, routesVersionMatch[1], 'routes.json');
    }

    const toolsVersionMatch = path.match(/^\/v1\/tools\/([^/]+)$/);
    if (toolsVersionMatch) {
      return handleVersionedArtifact(env, toolsVersionMatch[1], 'tools.json');
    }

    const clientMatch = path.match(/^\/v1\/client\/([^/]+)\/latest$/);
    if (clientMatch) {
      return handleClientLatest(clientMatch[1]);
    }

    const skillMatch = path.match(/^\/v1\/skill\/([^/]+)$/);
    if (skillMatch) {
      return handleSkill(skillMatch[1]);
    }

    if (path === '/v1/effective-contract/preview') {
      return handleEffectiveContractPreview(url, env);
    }

    return notFound(`Unknown route: ${path}`);
  },
} satisfies ExportedHandler<Env>;
